Repository Luxtelligence/lxt_pdk_gf, pull requests merged in 2024-11, with the labels that each got.

#48 Directional couplers
  CHANGELOG.md
  docs/notebooks/die_assembled_CLchip_fr_e8f9967c.gds
  docs/notebooks/models.ipynb
  lnoi400/cells.py
  lnoi400/data/directional_coupler_balanced.json
  lnoi400/models.py
  lnoi400/spline.py
  pyproject.toml
  tests/gds_ref/bend_S_spline_varying_width.gds
  tests/gds_ref/directional_coupler_balanced.gds
  tests/test_components/test_settings_L_turn_bend_.yml
  tests/test_components/test_settings_U_bend_racetrack_.yml
  tests/test_components/test_settings_bend_S_spline_varying_width_.yml
  tests/test_components/test_settings_directional_coupler_balanced_.yml
Labels: documentation, enhancement

#62 Directional couplers corrected
  lnoi400/cells.py
  tests/test_components/test_settings_directional_coupler_balanced_.yml
Labels: bug

#71 Support 2x2 MMI in mzm_unbalanced cell
  lnoi400/cells.py
  pyproject.toml
  tests/gds_ref/mmi2x2_optimized1550.gds
  tests/test_components/test_settings_mmi2x2_optimized1550_.yml
Labels: bug, enhancement
